$script = <<-SCRIPT
yum -y update; yum -y install git;
cd /opt; git clone https://github.com/Dynatrace/easytrade.git
cd easytrade; docker compose up -d
SCRIPT

Vagrant.configure("2") do |config|

    #Transfert de port machine -> vm
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 5601, host: 5601
    config.vm.network "forwarded_port", guest: 9200, host: 9200
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "formation-dynatrace"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "formation-dynatrace"
    end

    #Definir le hostname de la VM
    config.vm.hostname = "formation-dynatrace"
    
    config.vm.box = "bento/centos-7"
    
    #Installer Docker et télécharger l'image alpine 
    config.vm.provision "docker" do |d|
        d.pull_images "nginx"
    end

    #Installer Dynatrace Easytrade 
    config.vm.provision "shell", inline: $script

end