$script = <<-SCRIPT
apt -y update; apt -y install git;
cd /opt; git clone https://github.com/RousselTM/easytrade
cd easytrade; docker compose up -d
SCRIPT

Vagrant.configure("2") do |config|

    #Transfert de port machine -> vm
    config.vm.network "forwarded_port", guest: 80, host: 80
    
    #Definir le nom de la machine dans vagrant. Replace default
    config.vm.define "formation-dynatrace"
    
    #Definir le provider 
    config.vm.provider "virtualbox" do |v|
        #Definir le nom de la VM dans le provider en remplacement de celui par defaut
        v.name = "formation-dynatrace"
    end

    #Definir le hostname de la VM
    config.vm.hostname = "formation-dynatrace"
    
    config.vm.box = "bento/ubuntu-24.04"
    
    # Installation de Docker
    config.vm.provision "docker"

    #Installer Dynatrace Easytrade 
    config.vm.provision "shell", inline: $script

end